#!/usr/bin/env bash
# Writes Google Maps API keys for iOS (Secrets.xcconfig) and Android (local.properties).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KEY="${1:-}"

if [[ -z "${KEY}" ]]; then
  echo "Usage: bash scripts/setup_google_maps_key.sh YOUR_GOOGLE_MAPS_API_KEY"
  echo ""
  echo "Get a key: https://console.cloud.google.com/ → APIs & Services → Credentials"
  echo "Enable: Maps SDK for iOS, Maps SDK for Android (and billing on the project)."
  exit 1
fi

IOS_SECRETS="${ROOT}/ios/Flutter/Secrets.xcconfig"
ANDROID_PROPS="${ROOT}/android/local.properties"

cat > "${IOS_SECRETS}" <<EOF
// Generated by scripts/setup_google_maps_key.sh — do not commit (gitignored).
GOOGLE_MAPS_API_KEY=${KEY}
EOF
echo "Wrote ${IOS_SECRETS}"

touch "${ANDROID_PROPS}"
if grep -q '^GOOGLE_MAPS_API_KEY=' "${ANDROID_PROPS}" 2>/dev/null; then
  sed -i '' "s|^GOOGLE_MAPS_API_KEY=.*|GOOGLE_MAPS_API_KEY=${KEY}|" "${ANDROID_PROPS}"
else
  echo "GOOGLE_MAPS_API_KEY=${KEY}" >> "${ANDROID_PROPS}"
fi
echo "Updated ${ANDROID_PROPS}"

echo ""
echo "Next:"
echo "  cd \"${ROOT}/ios\" && pod install"
echo "  cd \"${ROOT}\" && bash scripts/run_ios_sim.sh"
